version: '2'
services:
        plex:
                container_name: plex
                image: plexinc/pms-docker
                restart: unless-stopped
                ports:
                        - 32400:32400/tcp
                        - 3005:3005/tcp
                        - 8324:8324/tcp
                        - 32469:32469/tcp
                        - 1900:1900/udp
                        - 32410:32410/udp
                        - 32412:32412/udp
                        - 32413:32413/udp
                        - 32414:32414/udp
                environment:
                        - PUID=1000
                        - PGID=1000
                        - TZ=Europe/Stockholm
                        - UMASK_SET=022 #optional
                        - PLEX_CLAIM=claim-zNVKfmzk35PQk-yNP1ox
                        - ADVERTISE_IP=http://192.168.1.119:32400/
                hostname: servo
                volumes:
                        - /home/morgan/docker/plex/config:/config
                        - /home/morgan/docker/plex/transcode:/transcode
                        - /mnt/nfs/media/sorterad_tv:/data/tvshows
                        - /mnt/stor/4k_tv:/data/tvshows1
                        - /mnt/nfs/media/sorterad_film:/data/movies
                        - /mnt/stor/4k_film:/data/movies1
                        - /mnt/nfs/media/sorterad_anime:/data/anime
