version: "2.1"
services:
        adguard:
                image: adguard/adguardhome
                container_name: adguard
                environment:
                        - PUID=1000
                        - PGID=1000
                        - TZ=Europe/Stockholm
                        - UMASK_SET=022 #optional
                volumes:
                        - /home/morgan/docker/adguard/conf:/opt/adguardhome/conf
                        - /home/morgan/docker/adguard/work:/opt/adguardhome/work

                ports:
                        - 53:53/udp
                        - 53:53/tcp
                        - 67:67/udp
                        - 68:68/tcp
                        - 68:68/udp
                        - 80:80
                        - 443:443
                        - 853:853
                        - 3000:3000
                network_mode: host
                restart: unless-stopped


